name: test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version-file: './go.mod'
          check-latest: true
      - name: Install deps
        run: go mod download
      - name: Run unit tests
        run: go test ./...
      - name: Run smoke test
        run: ./test.sh
